    const lyrics = [
{ text: "Mind over matter" },
{ text: "Does it matter to any of us?" },
{ text: "Don't change the subject" },
{ text: "I'm heavy on your love" },
{ text: "I missed that train" },
{ text: "New York City, it rains" },
{ text: "Fly to East L.A. in big jet planes" },
{ text: "You know you're on my mind?" },
{ text: "And if the world don't break" },
{ text: "I'll be shaking it" },
{ text: "'Cause I'm a young man after all" },
{ text: "And when the seasons change" },
{ text: "Will you stand by me?" },
{ text: "'Cause I'm a young man built to fall" },
{ text: "Mind over matter" },
{ text: "I'm in tatters thinking 'bout her" },
{ text: "Taste my disaster" },
{ text: "It's heavy on my tongue" },
{ text: "All the lights aglow" },
{ text: "Tokyo snows" },
{ text: "Go to watch the show" },
{ text: "Curtain's closed" },
{ text: "I'm watching you this time" },
{ text: "And if the world don't break" },
{ text: "I'll be shaking it" },
{ text: "'Cause I'm a young man after all" },
{ text: "And when the seasons change" },
{ text: "Will you stand by me?" },
{ text: "'Cause I'm a young man built to fall" },
{ text: "New York City, it rains" },
{ text: "(Fly to East L.A.)" },
{ text: "In big jet planes" },
{ text: "You know you're on my mind?" },
{ text: "(All the lights aglow)" },
{ text: "Tokyo snows" },
{ text: "(Go to watch the show)" },
{ text: "Curtain's closed" },
{ text: "I'm watching you this time" },
{ text: "Mind over matter" },
{ text: "Mind over matter" },
{ text: "You know you're on my mind?" },
{ text: "And if the world don't break" },
{ text: "I'll be shaking it" },
{ text: "'Cause I'm a young man after all" },
{ text: "And when the seasons change" },
{ text: "Will you stand by me" },
{ text: "(Fly to East L.A.)" },
{ text: "'Cause I'm a young man built to fall" },
{ text: "And if the world don't break" },
{ text: "Tokyo snows" },
{ text: "Go to watch the show; curtain's closed" },
{ text: "And when the seasons change" },
{ text: "Will you stand by me?" },
{ text: "'Cause I'm a young man built to fall" }
    ];
